language: python
dist: xenial

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8
    - python: 3.8-dev
    - python: nightly
    - os: osx
      language: generic
      env: MACPYTHON=3.6.3
    - python: 3.6
      env: CHECK_DOCS=1
    - python: 3.6
      env: CHECK_FORMATTING=1

script:
  - ci/travis.sh
